server/bima/lib/bima_web/router.ex
defmodule BimaWeb.Router do
	use BimaWeb, :router

	pipeline :browser do
		plug :accepts, ["html"]
		plug :fetch_session
		plug :fetch_flash
		plug :protect_from_forgery
		plug :put_secure_browser_headers
	end

	pipeline :api do
		plug :accepts, ["json"]
	end

  pipeline :authenticate do
    #plug BasicAuth, username: "bima", password: "bima"
    plug BimaWeb.Plugs.Auth
  end

  pipeline :admin_only do
    plug BimaWeb.Plugs.Auth, admin: true
  end

	scope "/", BimaWeb do
		pipe_through :browser

		get "/", PageController, :index
    get "/buy", SubscriptionController, :index

    delete "/logout", SessionController, :delete
  end

  scope "/", BimaWeb do
		pipe_through [:browser, BimaWeb.Plugs.Guest]

    resources "/register", UserController, only: [:create, :new, :show]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

	# Other scopes may use custom stacks.
	scope "/api", BimaWeb do
		pipe_through :api

		post "/sync", Api.SyncController, :sync
		get "/me", Api.MeController, :index
    #post "/app", Api.AppController, :create

		post "/blob", Api.BlobController, :create
		get "/blob/:code", Api.BlobController, :show
	end

  use Kaffy.Routes, scope: "/admin", pipe_through: [:browser, :admin_only]
end

server/bima/lib/bima_web/views/layout_view.ex
defmodule BimaWeb.LayoutView do
  use BimaWeb, :view
end

server/bima/lib/bima_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Bima · Native Desktop App for MFA and OTP Token</title>
    <%= csrf_meta_tag() %>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header class="navigation">
      <section class="container">
        <nav role="navigation">
          <ul class="navigation-list float-right">
            <li class="navigation-item"><a href="#pricing">Price</a></li>
            <li class="navigation-item"><a href="#faq">FAQ</a></li>
            <li class="navigation-item"><a class="button" href="#download">Download</a></li>
            <%= if signed_in?(@conn) do %>
              <li class="navigation-item"><%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %></li>
            <% end %>
          </ul>
        </nav>

        <a href="https://bima.getopty.com/" class="navigation-title phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" width="32" height="32"/>
          <h1 class="title">Bima</h1>
        </a>
      </section>
    </header>

    <main role="alert" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </main>

    <%= render @view_module, @view_template, assigns %>

    <footer class="footer"><section class="container"><p class="copyright">Build by <a href="https://betterdev.link" rel="noopener" target="_blank" title="Opty - DevOps consulting">Vinh</a>. © 2020 <a href="https://github.com/milligram/milligram#license" rel="noopener" target="_blank" title="MIT License">Opty LLC</a>.</p><nav class="nav"></nav></section></footer>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>