server/bima/lib/bima_web/router.ex
defmodule BimaWeb.Router do
	use BimaWeb, :router

	pipeline :browser do
		plug :accepts, ["html"]
		plug :fetch_session
		plug :fetch_flash
		plug :protect_from_forgery
		plug :put_secure_browser_headers
	end

	pipeline :api do
		plug :accepts, ["json"]
	end

  pipeline :authenticate do
    #plug BasicAuth, username: "bima", password: "bima"
    plug BimaWeb.Plugs.Auth
  end

  pipeline :admin_only do
    plug BimaWeb.Plugs.Auth, admin: true
  end

	scope "/", BimaWeb do
		pipe_through :browser

		get "/", PageController, :index
    get "/buy", SubscriptionController, :index

    delete "/logout", SessionController, :delete
  end

  scope "/", BimaWeb do
		pipe_through [:browser, BimaWeb.Plugs.Guest]

    resources "/register", UserController, only: [:create, :new, :show]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

	# Other scopes may use custom stacks.
	scope "/api", BimaWeb do
		pipe_through :api

		post "/sync", Api.SyncController, :sync
		get "/me", Api.MeController, :index
    #post "/app", Api.AppController, :create

		post "/blob", Api.BlobController, :create
		get "/blob/:code", Api.BlobController, :show
	end

  use Kaffy.Routes, scope: "/admin", pipe_through: [:browser, :admin_only]
end

server/bima/lib/bima_web/controllers/session_controller.ex
defmodule BimaWeb.SessionController do
  use BimaWeb, :controller

  alias Bima.Accounts.Auth
  alias Bima.Repo

  def new(conn, _params) do
    render(conn, "new.html")
  end

  @spec create(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create(conn, %{"session" => auth_params}) do
    case Auth.login(auth_params, Repo) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "Signed in successfully.")
        |> redirect(to: "/")
      :error ->
        conn
        |> put_flash(:error, "There was a problem with your username/password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:current_user_id)
    |> put_flash(:info, "Signed out successfully.")
    |> redirect(to: Routes.session_path(conn, :new))
  end
end

server/bima/lib/bima_web/views/session_view.ex
defmodule BimaWeb.SessionView do
  use BimaWeb, :view
end

server/bima/lib/bima_web/templates/session/new.html.eex
<section class='container box'>
  <div class='row'>
    <div class='card'>
      <div class='card-content'>
        <span class='card-title'>LOGIN</span>
        <div class='row card-form'>
          <%= form_for @conn, Routes.session_path(@conn, :new), [as: :session], fn f -> %>
            <%= text_input f, :email, placeholder: "Email" %>
            <%= password_input f, :password, placeholder: "Password" %>
            <%= submit "Submit", class: "btn right secondary-color" %>
            <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn secondary-color" %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</section>